"""Single source of truth for the plist-based tweaks.

Every tweak's definition (id, section, title, plist location, key, default
value, UI kind) lives here exactly once. ``tweak_loader`` builds the runtime
instances from these specs and the iOS tweaks page renders its rows from
them — adding a tweak means adding one entry here.
"""
from dataclasses import dataclass
from enum import Enum
from typing import Callable, Optional

from PySide6.QtCore import QT_TRANSLATE_NOOP

from .basic_plist_locations import FileLocation
from .tweak_names import TweakID


class Section(Enum):
    LIQUID_GLASS = "Liquid Glass"
    SPRINGBOARD = "SpringBoard"
    INTERNAL = "Internal Options"


class Kind(Enum):
    SWITCH = "switch"   # boolean toggle
    TEXT = "text"       # free-form text value
    NUMBER = "number"   # numeric value


# Feature (page) key each registry Section belongs to. Feeds HotLoad's
# FEATURE_TWEAKS so every registry tweak automatically joins its feature;
# the Sidebar uses the same keys to know which page owns a section.
SECTION_FEATURES: dict[Section, str] = {
    Section.LIQUID_GLASS: "Liquid Glass",
    Section.SPRINGBOARD: "Springboard",
    Section.INTERNAL: "Internal",
}


@dataclass(frozen=True)
class TweakSpec:
    id: TweakID
    section: Section
    title: str
    location: FileLocation
    key: str
    value: any = True          # value written when the tweak is enabled
    kind: Kind = Kind.SWITCH
    min_value: float = 0       # NUMBER kind only
    max_value: float = 999     # NUMBER kind only
    step: float = 1.0          # NUMBER kind only; not integral = decimal input
    min_version: Optional[str] = None
    max_version: Optional[str] = None
    iphone_only: bool = False
    ipad_only: bool = False
    factory: Optional[Callable[[], object]] = None  # overrides BasicPlistTweak
    description: Optional[str] = None  # detailed "what it does" tooltip
    disabled: bool = False  # True = tweak is cut off: never loaded, never applied, never rendered


def _t(id_: TweakID, section: Section, title: str, location: FileLocation,
       key: str, description: str = "", **kwargs) -> TweakSpec:
    # QT_TRANSLATE_NOOP marks the title for pyside6-lupdate; the actual
    # translation happens at render time (translators are not installed yet
    # when this module is imported).
    return TweakSpec(id=id_, section=section,
                     title=QT_TRANSLATE_NOOP("Nugget", title),
                     description=QT_TRANSLATE_NOOP("Nugget", description) if description else None,
                     location=location, key=key, **kwargs)


def _watchos_compatibility():
    from .tweak_classes import AdvancedPlistTweak
    return AdvancedPlistTweak(
        FileLocation.nanoregistry,
        keyValues={
            "IOS_PAIRING_EOL_MIN_PAIRING_COMPATIBILITY_VERSION_CHIPIDS": "",
            "maxPairingCompatibilityVersion": 37,
            "lastRestoreIdentifier": "CD97EEB8-BCD2-486B-BC13-C384E6B916C4",  # not sure if this is needed
            "minPairingCompatibilityVersionWithChipID": 1,
            "lastRestoreIdentifier_state": 0,
            "AdvertisingIdentifierSeed": "85E70251-1960-4DA0-A321-B68AC118FAB5",  # this prolly isn't needed either
            "minPairingCompatibilityVersion": 1
        })


def _usol(member: TweakID, title: str, kind: Kind = Kind.SWITCH, value=True, *,
          min_value: float = 0, max_value: float = 999, step: float = 1.0,
          description: str = "") -> TweakSpec:
    """UISolarium* debug / stacked-icon-motion tweak (.GlobalPreferences, iOS 27).

    The plist key is derived from the TweakID name (``UISolarium`` + name), so
    the enum member and the written key can never drift apart.
    """
    return _t(member, Section.LIQUID_GLASS, title, GP,
              "UISolarium" + member.name,
              description=description, kind=kind, value=value,
              min_value=min_value, max_value=max_value, step=step,
              min_version="27.0")


GP = FileLocation.globalPreferences

SPECS: tuple[TweakSpec, ...] = (
    # --- Liquid Glass ---
    _t(TweakID.ForceSolariumFallback, Section.LIQUID_GLASS, "Force Solarium Fallback", GP, "SolariumForceFallback",
       description=QT_TRANSLATE_NOOP("Nugget", "Forces the older Solarium rendering path instead of the newer one. Useful for troubleshooting or for devices where the current Solarium engine misbehaves on iOS 26."),
       min_version="26.0", max_version="26.99"),
    _t(TweakID.IgnoreSolariumLinkedOnCheck, Section.LIQUID_GLASS, "Ignore Solarium Linked-On Check", GP, "com.apple.SwiftUI.IgnoreSolariumLinkedOnCheck",
       description=QT_TRANSLATE_NOOP("Nugget", "Ignores the compile-time (linked-on) SDK version check for Solarium, allowing Liquid Glass features to run that would otherwise be gated by the SDK an app was built with."),
       min_version="26.0"),
    _t(TweakID.ForceSolariumIntelligence, Section.LIQUID_GLASS, "Force Solarium Intelligence", GP, "SolariumForceIntelligence",
       description=QT_TRANSLATE_NOOP("Nugget", "Forces the experimental Solarium 'Intelligence' rendering features (adaptive, machine-driven effects) on iOS 27 where they are not enabled by default."),
       min_version="27.0"),
    _t(TweakID.ForceEnhancedSpeculars, Section.LIQUID_GLASS, "Force Enhanced Speculars", GP, "SolariumForceEnhancedSpeculars",
       description=QT_TRANSLATE_NOOP("Nugget", "Enables the enhanced specular (highlight and reflection) rendering pass that is normally only used on the most capable devices."),
       min_version="27.0"),
    _t(TweakID.UISolariumFallback, Section.LIQUID_GLASS, "UI Solarium Fallback", GP, "UISolariumForceFallback",
       description=QT_TRANSLATE_NOOP("Nugget", "Forces UIKit to use the fallback Solarium path when rendering UI. Can fix broken or glitchy system UI on some iOS 27 devices."),
       min_version="27.0"),
    _t(TweakID.IgnoreSolariumHardwareCheck, Section.LIQUID_GLASS, "Ignore Solarium Hardware Check", GP, "com.apple.SwiftUI.IgnoreSolariumHardwareCheck",
       description=QT_TRANSLATE_NOOP("Nugget", "Disables the hardware capability check for Solarium, enabling Liquid Glass effects on devices officially considered too weak."),
       min_version="27.0"),
    _t(TweakID.IgnoreSolariumOptOut, Section.LIQUID_GLASS, "Ignore Solarium Opt-Out", GP, "com.apple.SwiftUI.IgnoreSolariumOptOut",
       description=QT_TRANSLATE_NOOP("Nugget", "Ignores the system opt-out flag for Solarium, re-enabling Liquid Glass on devices or firmware that have it switched off."),
       min_version="27.0"),
    _t(TweakID.DisallowGlassButtons, Section.LIQUID_GLASS, "Disallow Glass Buttons", GP, "SBDisallowGlassButtons",
       description=QT_TRANSLATE_NOOP("Nugget", "Prevents the Liquid Glass material from being applied to system buttons, keeping the old solid button style."),
       min_version="27.0"),
    _t(TweakID.DisallowGlassLockScreen, Section.LIQUID_GLASS, "Disallow Glass Lock Screen", GP, "SBDisallowGlassLockScreen",
       description=QT_TRANSLATE_NOOP("Nugget", "Prevents the Liquid Glass material from being applied to the Lock Screen, keeping the old lock screen look."),
       min_version="27.0"),
    _t(TweakID.DisableSpecularEverywhere, Section.LIQUID_GLASS, "Disable Specular Everywhere", GP, "SBDisableSpecularEverywhere",
       description=QT_TRANSLATE_NOOP("Nugget", "Disables the specular (glossy reflection) rendering everywhere, removing the shiny glass highlight from Liquid Glass surfaces."),
       min_version="27.0"),
    _t(TweakID.NoLiquidClock, Section.LIQUID_GLASS, "Disable Liquid Glass on LS Clock", GP, "SBDisallowGlassTime",
       description=QT_TRANSLATE_NOOP("Nugget", "Renders the Lock Screen clock in the old solid style instead of with the Liquid Glass / dew effect."),
       min_version="26.0"),
    _t(TweakID.NoLiquidDock, Section.LIQUID_GLASS, "Disable Liquid Glass on Dock", GP, "SBDisableGlassDock",
       description=QT_TRANSLATE_NOOP("Nugget", "Renders the Home Screen dock in the old solid style instead of with the Liquid Glass material."),
       min_version="26.0"),
    _t(TweakID.DisableSpecularMotion, Section.LIQUID_GLASS, "Disable Specular Motion", GP, "SBDisableSpecularEverywhereUsingLSSAssertion",
       description=QT_TRANSLATE_NOOP("Nugget", "Disables the motion-based specular effect on the Lock Screen, so the moving light reflection no longer shifts as you tilt your device."),
       min_version="26.0"),
    _t(TweakID.DisableOuterRefraction, Section.LIQUID_GLASS, "Disable Outer Refraction", GP, "SolariumDisableOuterRefraction",
       description=QT_TRANSLATE_NOOP("Nugget", "Disables the outer refraction (the liquid bending of content at the glass edge) for a cleaner, less distorted look."),
       min_version="26.0"),
    _t(TweakID.DisableSolariumHDR, Section.LIQUID_GLASS, "Disable Solarium HDR", GP, "SolariumAllowHDR", value=False,
       description=QT_TRANSLATE_NOOP("Nugget", "Disables HDR tone-mapping in the Solarium renderer. Can fix washed-out or over-bright Liquid Glass areas. Enabled when the switch is OFF."),
       min_version="26.0"),
    # Home Screen glass family. These sit in the same accessor/key table as the
    # SB* keys above — the one SpringBoard itself persists into
    # com.apple.springboard — and SpringBoard reads them through the standard
    # defaults search chain, so NSGlobalDomain (GP) reaches them too.
    _t(TweakID.DisableWidgetSpecular, Section.LIQUID_GLASS, "Disable Widget Specular",
       GP, "SBDisableWidgetSpecular",
       description=QT_TRANSLATE_NOOP("Nugget", "Removes the specular (glossy highlight) pass from Home Screen widget icons, so they no longer catch a moving highlight."),
       min_version="27.0"),
    _t(TweakID.DisableDockSpecular, Section.LIQUID_GLASS, "Disable Dock Specular",
       GP, "SBDisableDockSpecular",
       description=QT_TRANSLATE_NOOP("Nugget", "Removes the specular highlight from the Home Screen dock, leaving the glass material without its glossy sheen."),
       min_version="27.0"),
    _t(TweakID.DisableFolderSpecular, Section.LIQUID_GLASS, "Disable Folder Specular",
       GP, "SBDisableFolderSpecular",
       description=QT_TRANSLATE_NOOP("Nugget", "Removes the specular highlight from Home Screen folder backgrounds."),
       min_version="27.0"),
    _t(TweakID.ExcludeClearGlassShadows, Section.LIQUID_GLASS, "Exclude All Clear Glass Shadows",
       GP, "SBExcludeAllClearGlassShadows",
       description=QT_TRANSLATE_NOOP("Nugget", "Drops every shadow the Clear Glass material casts. Useful when the shadows make light wallpapers look muddy."),
       min_version="27.0"),
    _t(TweakID.ExcludeDockShadow, Section.LIQUID_GLASS, "Exclude Dock Shadow",
       GP, "SBExcludeDockShadow",
       description=QT_TRANSLATE_NOOP("Nugget", "Removes the drop shadow under the Home Screen dock."),
       min_version="27.0"),
    _t(TweakID.ExcludeSearchShadow, Section.LIQUID_GLASS, "Exclude Search Shadow",
       GP, "SBExcludeSearchShadow",
       description=QT_TRANSLATE_NOOP("Nugget", "Removes the drop shadow under the Home Screen search field."),
       min_version="27.0"),
    _t(TweakID.UseFlatIconsEverywhere, Section.LIQUID_GLASS, "Use Flat Icons Everywhere",
       GP, "SBUseFlatIconsEverywhere",
       description=QT_TRANSLATE_NOOP("Nugget", "Draws Home Screen icons in the flat style instead of the glass/3D look."),
       min_version="27.0"),

    # --- Tier 3: SwiftUI / UIKit debug switches (UserDefaults -> GP) ---
    _t(TweakID.GlassContainerLogging, Section.LIQUID_GLASS,
       "Glass Container Logging", GP,
       "com.apple.SwiftUI.GlassContainerLogging",
       description=QT_TRANSLATE_NOOP("Nugget", "Enables glass container debug logging (com.apple.SwiftUI UserDefaults key)."),
       min_version="27.0"),
    _t(TweakID.FlexiGlassMacOS, Section.LIQUID_GLASS,
       "Flexi Glass (macOS path)", GP,
       "com.apple.SwiftUI.FlexiGlassMacOS",
       description=QT_TRANSLATE_NOOP("Nugget", "Enables FlexiGlass on the macOS-side rendering path (com.apple.SwiftUI UserDefaults key)."),
       min_version="27.0"),
    _t(TweakID.FlexiGlassMacOSPointer, Section.LIQUID_GLASS,
       "Flexi Glass (macOS Pointer)", GP,
       "com.apple.SwiftUI.FlexiGlassMacOSPointer",
       description=QT_TRANSLATE_NOOP("Nugget", "Enables the pointer variant of FlexiGlass on the macOS-side path (com.apple.SwiftUI UserDefaults key)."),
       min_version="27.0"),
    _t(TweakID.InvisibilitySuppressesGlass, Section.LIQUID_GLASS,
       "Invisible View Suppresses Glass", GP,
       "com.apple.UIKit.InvisibilitySuppressesGlass",
       description=QT_TRANSLATE_NOOP("Nugget", "When enabled, invisible views suppress the glass effect applied to them (com.apple.UIKit UserDefaults key)."),
       min_version="27.0"),
    _t(TweakID.EnableGlassEffectBridgeLayers, Section.LIQUID_GLASS,
       "Enable Glass Effect Bridge Layers", GP,
       "EnableGlassEffectBridgeLayers",
       description=QT_TRANSLATE_NOOP("Nugget", "Enables glass effect bridge layers (bare UserDefaults key, read via NSGlobalDomain fallback)."),
       min_version="27.0"),
    _t(TweakID.EnableGaussianGlassEffectBridgeLayers, Section.LIQUID_GLASS,
       "Enable Gaussian Glass Bridge Layers", GP,
       "EnableGaussianGlassEffectBridgeLayers",
       description=QT_TRANSLATE_NOOP("Nugget", "Enables gaussian glass effect bridge layers (bare UserDefaults key, read via NSGlobalDomain fallback)."),
       min_version="27.0"),
    _t(TweakID.UnifiedSystemBackgroundColorsEnabled, Section.LIQUID_GLASS,
       "Unified System Background Colors", GP,
       "UnifiedSystemBackgroundColorsEnabled",
       description=QT_TRANSLATE_NOOP("Nugget", "Enables unified system background colors across the system (bare UserDefaults key, read via NSGlobalDomain fallback)."),
       min_version="27.0"),
    _t(TweakID.UnaryGlassContainerEnabled, Section.LIQUID_GLASS,
       "Unary Glass Container", GP,
       "UnaryGlassContainerEnabled",
       description=QT_TRANSLATE_NOOP("Nugget", "Enables the unary glass container (bare UserDefaults key, read via NSGlobalDomain fallback)."),
       min_version="27.0"),
    _t(TweakID.EnableSolariumCompactChrome, Section.LIQUID_GLASS,
       "Enable Solarium Compact Chrome", GP,
       "EnableSolariumCompactChrome",
       description=QT_TRANSLATE_NOOP("Nugget", "Enables compact chrome in the Solarium renderer (UIKit debug cluster, bare UserDefaults key)."),
       min_version="27.0"),
    _t(TweakID.DisableSolariumCompactChrome, Section.LIQUID_GLASS,
       "Disable Solarium Compact Chrome", GP,
       "DisableSolariumCompactChrome",
       description=QT_TRANSLATE_NOOP("Nugget", "Disables compact chrome in the Solarium renderer (UIKit debug cluster, bare UserDefaults key)."),
       min_version="27.0"),

    # --- Tier 4: DesignLibrary glass recipes (GP) ---
    _t(TweakID.SolariumIncreasedDiffusion, Section.LIQUID_GLASS,
       "Increased Diffusion", GP, "SolariumIncreasedDiffusion",
       description=QT_TRANSLATE_NOOP("Nugget", "Increases the diffusion / legibility axis of the glass recipe, orthogonal to the tint amount."),
       min_version="27.0"),
    _t(TweakID.SolariumUseDisplayAngle, Section.LIQUID_GLASS,
       "Use Display Angle", GP, "SolariumUseDisplayAngle",
       description=QT_TRANSLATE_NOOP("Nugget", "Uses the display angle to drive glass highlights."),
       min_version="27.0"),
    _t(TweakID.SolariumTintMask, Section.LIQUID_GLASS,
       "Tint Mask", GP, "SolariumTintMask",
       description=QT_TRANSLATE_NOOP("Nugget", "Enables the Solarium tint mask."),
       min_version="27.0"),
    _t(TweakID.SolariumBackgroundFilter, Section.LIQUID_GLASS,
       "Background Filter", GP, "SolariumBackgroundFilter",
       description=QT_TRANSLATE_NOOP("Nugget", "Enables the Solarium background filter."),
       min_version="27.0"),
    _t(TweakID.SolariumHighlightWhite, Section.LIQUID_GLASS,
       "Highlight White Point", GP, "SolariumHighlightWhite",
       value=1.0, kind=Kind.NUMBER, min_value=0.0, max_value=1.0, step=0.05,
       description=QT_TRANSLATE_NOOP("Nugget", "White point of the glass highlight (0.0 to 1.0). Defaults to 1.0 (full white). Type inferred; unverified on-device."),
       min_version="27.0"),
    _t(TweakID.SolariumLiveTuning, Section.LIQUID_GLASS,
       "Live Tuning", GP, "SolariumLiveTuning",
       description=QT_TRANSLATE_NOOP("Nugget", "Enables the Solarium live tuning switch — allows real-time glass parameter changes."),
       min_version="27.0"),
    _t(TweakID.SolariumHierarchicalStyle, Section.LIQUID_GLASS,
       "Solarium Hierarchical Style", GP, "SolariumHierarchicalStyle",
       value=1, kind=Kind.NUMBER, min_value=0, max_value=10, step=1,
       description=QT_TRANSLATE_NOOP("Nugget", "Sets the Solarium hierarchical glass style level (integer 0–10). Type inferred; unverified on-device."),
       min_version="27.0"),
    _t(TweakID.GlassHierarchicalStyle, Section.LIQUID_GLASS,
       "Glass Hierarchical Style", GP, "GlassHierarchicalStyle",
       value=1, kind=Kind.NUMBER, min_value=0, max_value=10, step=1,
       description=QT_TRANSLATE_NOOP("Nugget", "Alternative entry for the hierarchical glass style level (integer 0–10). Type inferred; unverified on-device."),
       min_version="27.0"),
    _t(TweakID.GlassVisualDebug, Section.LIQUID_GLASS,
       "Glass Visual Debug", GP, "GlassVisualDebug",
       description=QT_TRANSLATE_NOOP("Nugget", "Overlays glass visual debug information on screen (debug/tuning key)."),
       min_version="27.0"),
    _t(TweakID.GlassVisualWarnings, Section.LIQUID_GLASS,
       "Glass Visual Warnings", GP, "GlassVisualWarnings",
       description=QT_TRANSLATE_NOOP("Nugget", "Shows glass visual warnings overlay (debug/tuning key)."),
       min_version="27.0"),
    _t(TweakID.BlurFillExperiment, Section.LIQUID_GLASS,
       "Blur Fill Experiment", GP, "blurFillExperiment",
       description=QT_TRANSLATE_NOOP("Nugget", "Enables the blur fill experiment path (debug/tuning key, exact behavior unknown)."),
       min_version="27.0"),
    _t(TweakID.AdaptiveGlassHysteresisDarkRange, Section.LIQUID_GLASS,
       "Adaptive Glass Hysteresis (Dark Range)", GP,
       "AdaptiveGlassHysteresisDarkRangeArray",
       value="", kind=Kind.TEXT,
       description=QT_TRANSLATE_NOOP("Nugget", "Adaptive glass hysteresis dark range — list of floating-point thresholds. Type inferred as Array<Number>; written as text for this test UI, so may be ignored by the framework. Unverified on-device."),
       min_version="27.0"),
    _t(TweakID.AdaptiveGlassHysteresisLightRange, Section.LIQUID_GLASS,
       "Adaptive Glass Hysteresis (Light Range)", GP,
       "AdaptiveGlassHysteresisLightRangeArray",
       value="", kind=Kind.TEXT,
       description=QT_TRANSLATE_NOOP("Nugget", "Adaptive glass hysteresis light range — list of floating-point thresholds. Type inferred as Array<Number>; written as text for this test UI, so may be ignored by the framework. Unverified on-device."),
       min_version="27.0"),
    _t(TweakID.CalistogaLargeRefraction, Section.LIQUID_GLASS,
       "Large Refraction (Calistoga)", GP, "CalistogaLargeRefraction",
       description=QT_TRANSLATE_NOOP("Nugget", "Enables the large refraction effect (Calistoga = internal code name for the glass material)."),
       min_version="27.0"),
    _t(TweakID.CalistogaRegularClearer, Section.LIQUID_GLASS,
       "Regular Tier Clearer (Calistoga)", GP, "CalistogaRegularClearer",
       description=QT_TRANSLATE_NOOP("Nugget", "Makes the regular tier glass render clearer (Calistoga)."),
       min_version="27.0"),
    _t(TweakID.CalistogaBackdropMarginIncludesBlur, Section.LIQUID_GLASS,
       "Backdrop Margin Includes Blur (Calistoga)", GP,
       "CalistogaBackdropMarginIncludesBlur",
       description=QT_TRANSLATE_NOOP("Nugget", "Backdrop margin calculation includes the blur extent (Calistoga)."),
       min_version="27.0"),
    _t(TweakID.CalistogaAllowLumaTracking, Section.LIQUID_GLASS,
       "Allow Luma Tracking (Calistoga)", GP, "CalistogaAllowLumaTracking",
       description=QT_TRANSLATE_NOOP("Nugget", "Allows luminance (luma) tracking to drive glass adaptation (Calistoga)."),
       min_version="27.0"),
    _t(TweakID.CalistogaSidebarAccentOpacity, Section.LIQUID_GLASS,
       "Sidebar Accent Opacity (Calistoga)", GP, "CalistogaSidebarAccentOpacity",
       value=1.0, kind=Kind.NUMBER, min_value=0.0, max_value=1.0, step=0.05,
       description=QT_TRANSLATE_NOOP("Nugget", "Opacity of the sidebar accent under the glass material (0.0–1.0, Calistoga). Type inferred; unverified on-device."),
       min_version="27.0"),
    _t(TweakID.CalistogaPerceptualBackdropScale, Section.LIQUID_GLASS,
       "Perceptual Backdrop Scale (Calistoga)", GP,
       "CalistogaPerceptualBackdropScale",
       value=1.0, kind=Kind.NUMBER, min_value=0.0, max_value=2.0, step=0.05,
       description=QT_TRANSLATE_NOOP("Nugget", "Perceptual backdrop scale factor for the glass material (0.0–2.0, Calistoga). Type inferred; unverified on-device."),
       min_version="27.0"),
    _t(TweakID.CalistogaKeyboardGlass, Section.LIQUID_GLASS,
       "Keyboard Glass (Calistoga)", GP, "CalistogaKeyboardGlass",
       description=QT_TRANSLATE_NOOP("Nugget", "Applies the glass material to the keyboard (Calistoga)."),
       min_version="27.0"),
    _t(TweakID.CalistogaCameraGlass, Section.LIQUID_GLASS,
       "Camera Glass (Calistoga)", GP, "CalistogaCameraGlass",
       description=QT_TRANSLATE_NOOP("Nugget", "Applies the glass material to the camera surface (Calistoga)."),
       min_version="27.0"),

    # --- Tier 5: UISolarium* floating content / stacked icon motion ---
    # Floating content view
    _usol(TweakID.FloatingContentViewSpecularHighlightOpacity,
          "Floating Specular Highlight Opacity",
          Kind.NUMBER, value=0.0, min_value=0.0, max_value=1.0, step=0.05,
          description=QT_TRANSLATE_NOOP("Nugget", "Opacity of the specular highlight on floating content views (0 = off, 1 = full). Type inferred; unverified on-device.")),
    _usol(TweakID.FloatingContentViewUnfocusedBorderOpacity,
          "Floating Unfocused Border Opacity",
          Kind.NUMBER, value=0.0, min_value=0.0, max_value=1.0, step=0.05,
          description=QT_TRANSLATE_NOOP("Nugget", "Opacity of the unfocused border on floating content views. Type inferred; unverified on-device.")),
    _usol(TweakID.FloatingContentViewUnfocusedBorderWidth,
          "Floating Unfocused Border Width",
          Kind.NUMBER, value=1.0, min_value=0.0, max_value=20.0, step=0.5,
          description=QT_TRANSLATE_NOOP("Nugget", "Width of the unfocused border on floating content views. Type inferred; unverified on-device.")),
    _usol(TweakID.FloatingContentViewEnableBackgroundFills,
          "Floating Background Fills",
          description=QT_TRANSLATE_NOOP("Nugget", "Enables background fills on floating content views.")),
    _usol(TweakID.FloatingContentViewDebugBackgroundFills,
          "Floating Debug Background Fills",
          description=QT_TRANSLATE_NOOP("Nugget", "Enables debug background fills on floating content views (debug variant of the above).")),
    _usol(TweakID.FloatingContentViewPunchoutShadow,
          "Floating Punchout Shadow",
          description=QT_TRANSLATE_NOOP("Nugget", "Enables punchout shadow on floating content views.")),
    _usol(TweakID.FloatingContentViewModifyTransformMode,
          "Floating Transform Mode",
          Kind.NUMBER, value=1, min_value=0, max_value=10, step=1,
          description=QT_TRANSLATE_NOOP("Nugget", "Transform mode for floating content view stacking (integer). Type inferred; unverified on-device.")),
    _usol(TweakID.FloatingContentViewOverrideRotationX,
          "Floating Override Rotation X",
          Kind.NUMBER, value=0.0, min_value=-90.0, max_value=90.0, step=1.0,
          description=QT_TRANSLATE_NOOP("Nugget", "Forced X-axis rotation for floating content views (degrees). Type inferred; unverified on-device.")),
    _usol(TweakID.FloatingContentViewOverrideRotationY,
          "Floating Override Rotation Y",
          Kind.NUMBER, value=0.0, min_value=-90.0, max_value=90.0, step=1.0,
          description=QT_TRANSLATE_NOOP("Nugget", "Forced Y-axis rotation for floating content views (degrees). Type inferred; unverified on-device.")),
    _usol(TweakID.FloatingContentViewOverrideTranslationX,
          "Floating Override Translation X",
          Kind.NUMBER, value=0.0, min_value=-1000.0, max_value=1000.0, step=1.0,
          description=QT_TRANSLATE_NOOP("Nugget", "Forced X-axis translation for floating content views (points). Type inferred; unverified on-device.")),
    _usol(TweakID.FloatingContentViewOverrideTranslationY,
          "Floating Override Translation Y",
          Kind.NUMBER, value=0.0, min_value=-1000.0, max_value=1000.0, step=1.0,
          description=QT_TRANSLATE_NOOP("Nugget", "Forced Y-axis translation for floating content views (points). Type inferred; unverified on-device.")),
    _usol(TweakID.FloatingContentViewModifyRotationStrength,
          "Floating Rotation Strength",
          Kind.NUMBER, value=1.0, min_value=0.0, max_value=1.0, step=0.05,
          description=QT_TRANSLATE_NOOP("Nugget", "Multiplier for the rotation applied to floating content views. Type inferred; unverified on-device.")),
    _usol(TweakID.FloatingContentViewModifyTranslationStrength,
          "Floating Translation Strength",
          Kind.NUMBER, value=1.0, min_value=0.0, max_value=1.0, step=0.05,
          description=QT_TRANSLATE_NOOP("Nugget", "Multiplier for the translation applied to floating content views. Type inferred; unverified on-device.")),
    # Focus specular highlight
    _usol(TweakID.FocusSpecularHighlightMaxSize,
          "Focus Specular Highlight Max Size",
          Kind.NUMBER, value=1.0, min_value=0.0, max_value=1.0, step=0.05,
          description=QT_TRANSLATE_NOOP("Nugget", "Maximum size of the focus specular highlight (0–1). Type inferred; unverified on-device.")),
    _usol(TweakID.FocusSpecularHighlightScaleFactor,
          "Focus Specular Highlight Scale Factor",
          Kind.NUMBER, value=1.0, min_value=0.0, max_value=2.0, step=0.05,
          description=QT_TRANSLATE_NOOP("Nugget", "Scale factor of the focus specular highlight. Type inferred; unverified on-device.")),
    _usol(TweakID.FocusSpecularHighlightSensitivity,
          "Focus Specular Highlight Sensitivity",
          Kind.NUMBER, value=1.0, min_value=0.0, max_value=1.0, step=0.05,
          description=QT_TRANSLATE_NOOP("Nugget", "Sensitivity of the focus specular highlight to focus changes. Type inferred; unverified on-device.")),
    _usol(TweakID.FocusSpecularHighlightNormalizedPositionX,
          "Focus Specular Highlight Position X",
          Kind.NUMBER, value=0.5, min_value=0.0, max_value=1.0, step=0.05,
          description=QT_TRANSLATE_NOOP("Nugget", "Normalized X position of the focus specular highlight (0–1). Type inferred; unverified on-device.")),
    _usol(TweakID.FocusSpecularHighlightNormalizedPositionY,
          "Focus Specular Highlight Position Y",
          Kind.NUMBER, value=0.5, min_value=0.0, max_value=1.0, step=0.05,
          description=QT_TRANSLATE_NOOP("Nugget", "Normalized Y position of the focus specular highlight (0–1). Type inferred; unverified on-device.")),
    # New stacked image (3D parallax) family
    _usol(TweakID.NewStackedImageRenderingEnabled,
          "New Stacked Image Rendering",
          description=QT_TRANSLATE_NOOP("Nugget", "Enables the new stacked image rendering pipeline for Home Screen icons (3D parallax layering).")),
    _usol(TweakID.NewStackedImageFiltersEnabled,
          "Stacked Image Filters",
          description=QT_TRANSLATE_NOOP("Nugget", "Enables image filters in the stacked image rendering pipeline.")),
    _usol(TweakID.NewStackedImage3DTransformsEnabled,
          "Stacked Image 3D Transforms",
          description=QT_TRANSLATE_NOOP("Nugget", "Enables 3D transforms in the stacked image rendering pipeline.")),
    _usol(TweakID.NewStackedImage3DTransformedGlassLayer,
          "Stacked Image 3D Glass Layer",
          description=QT_TRANSLATE_NOOP("Nugget", "Enables the 3D-transformed glass layer in the stacked image rendering pipeline.")),
    _usol(TweakID.NewStackedImageSpecularEnabled,
          "Stacked Image Specular",
          description=QT_TRANSLATE_NOOP("Nugget", "Enables specular highlights on stacked images.")),
    _usol(TweakID.NewStackedImageSpecularOpacity,
          "Stacked Image Specular Opacity",
          Kind.NUMBER, value=0.0, min_value=0.0, max_value=1.0, step=0.05,
          description=QT_TRANSLATE_NOOP("Nugget", "Opacity of specular highlights on stacked images (0 = off). Type inferred; unverified on-device.")),
    _usol(TweakID.NewStackedImageRadiosityEnabled,
          "Stacked Image Radiosity",
          description=QT_TRANSLATE_NOOP("Nugget", "Enables radiosity (color bleed from nearby surfaces) in the stacked image pipeline.")),
    _usol(TweakID.NewStackedImageForceAdjustMotionForSize,
          "Stacked Image Adjust Motion for Size",
          description=QT_TRANSLATE_NOOP("Nugget", "Forces the stacked image motion adjustment to adapt to icon size.")),
    _usol(TweakID.NewStackedImageForceDefaultScaleSizeIncrease,
          "Stacked Image Default Scale Increase",
          description=QT_TRANSLATE_NOOP("Nugget", "Forces the default scale size increase in the stacked image rendering.")),
    _usol(TweakID.NewStackedImageInnerParallaxScale,
          "Stacked Image Inner Parallax Scale",
          Kind.NUMBER, value=1.0, min_value=0.0, max_value=1.0, step=0.05,
          description=QT_TRANSLATE_NOOP("Nugget", "Inner parallax scale of the stacked image (0–1). Type inferred; unverified on-device.")),
    _usol(TweakID.NewStackedImageAsymmetricScale,
          "Stacked Image Asymmetric Scale",
          Kind.NUMBER, value=1.0, min_value=0.0, max_value=1.0, step=0.05,
          description=QT_TRANSLATE_NOOP("Nugget", "Asymmetric scale of the stacked image (controls non-uniform X/Y scaling). Type inferred; unverified on-device.")),
    _usol(TweakID.NewStackedImageProgressiveScale,
          "Stacked Image Progressive Scale",
          Kind.NUMBER, value=1.0, min_value=0.0, max_value=1.0, step=0.05,
          description=QT_TRANSLATE_NOOP("Nugget", "Progressive scale of the stacked image across depth layers. Type inferred; unverified on-device.")),
    _usol(TweakID.NewStackedImageAdditionalTranslation,
          "Stacked Image Additional Translation",
          Kind.NUMBER, value=0.0, min_value=0.0, max_value=100.0, step=1.0,
          description=QT_TRANSLATE_NOOP("Nugget", "Additional translation applied to stacked images (points). Type inferred; unverified on-device.")),
    _usol(TweakID.NewStackedImageFocusedAdditionalScaleAmount,
          "Stacked Image Focused Scale Amount",
          Kind.NUMBER, value=1.0, min_value=0.0, max_value=2.0, step=0.05,
          description=QT_TRANSLATE_NOOP("Nugget", "Additional scale applied to the focused stacked image. Type inferred; unverified on-device.")),
    # Stacked image container defaults and modifiers
    _usol(TweakID.StackedImageContainerDefaultMaxDepth,
          "Stacked Container Max Depth",
          Kind.NUMBER, value=20.0, min_value=0.0, max_value=100.0, step=1.0,
          description=QT_TRANSLATE_NOOP("Nugget", "Default maximum depth of the stacked image container (points). Type inferred; unverified on-device.")),
    _usol(TweakID.StackedImageContainerDefaultRotationX,
          "Stacked Container Default Rotation X",
          Kind.NUMBER, value=0.0, min_value=-90.0, max_value=90.0, step=1.0,
          description=QT_TRANSLATE_NOOP("Nugget", "Default X-axis rotation of the stacked image container (degrees). Type inferred; unverified on-device.")),
    _usol(TweakID.StackedImageContainerDefaultRotationY,
          "Stacked Container Default Rotation Y",
          Kind.NUMBER, value=0.0, min_value=-90.0, max_value=90.0, step=1.0,
          description=QT_TRANSLATE_NOOP("Nugget", "Default Y-axis rotation of the stacked image container (degrees). Type inferred; unverified on-device.")),
    _usol(TweakID.StackedImageContainerDefaultTranslationX,
          "Stacked Container Default Translation X",
          Kind.NUMBER, value=0.0, min_value=-1000.0, max_value=1000.0, step=1.0,
          description=QT_TRANSLATE_NOOP("Nugget", "Default X-axis translation of the stacked image container (points). Type inferred; unverified on-device.")),
    _usol(TweakID.StackedImageContainerDefaultTranslationY,
          "Stacked Container Default Translation Y",
          Kind.NUMBER, value=0.0, min_value=-1000.0, max_value=1000.0, step=1.0,
          description=QT_TRANSLATE_NOOP("Nugget", "Default Y-axis translation of the stacked image container (points). Type inferred; unverified on-device.")),
    _usol(TweakID.StackedImageContainerModifyMaxDepthStrength,
          "Stacked Container Depth Strength",
          Kind.NUMBER, value=1.0, min_value=0.0, max_value=1.0, step=0.05,
          description=QT_TRANSLATE_NOOP("Nugget", "Multiplier for the maximum depth modification of the stacked image container. Type inferred; unverified on-device.")),
    _usol(TweakID.StackedImageContainerModifyRotationStrength,
          "Stacked Container Rotation Strength",
          Kind.NUMBER, value=1.0, min_value=0.0, max_value=1.0, step=0.05,
          description=QT_TRANSLATE_NOOP("Nugget", "Multiplier for the rotation modification of the stacked image container. Type inferred; unverified on-device.")),
    _usol(TweakID.StackedImageContainerModifyTranslationStrength,
          "Stacked Container Translation Strength",
          Kind.NUMBER, value=1.0, min_value=0.0, max_value=1.0, step=0.05,
          description=QT_TRANSLATE_NOOP("Nugget", "Multiplier for the translation modification of the stacked image container. Type inferred; unverified on-device.")),
    _usol(TweakID.StackedImageContainerModifyInnerParallaxScaleStrength,
          "Stacked Container Parallax Strength",
          Kind.NUMBER, value=1.0, min_value=0.0, max_value=1.0, step=0.05,
          description=QT_TRANSLATE_NOOP("Nugget", "Multiplier for the inner parallax scale modification of the stacked image container. Type inferred; unverified on-device.")),
    _usol(TweakID.StackedImageContainerModifyTransformMinWidth,
          "Stacked Container Transform Min Width",
          Kind.NUMBER, value=0.0, min_value=0.0, max_value=1000.0, step=1.0,
          description=QT_TRANSLATE_NOOP("Nugget", "Minimum width threshold for triggering stacked image container transforms. Type inferred; unverified on-device.")),
    _usol(TweakID.StackedImageContainerModifyTransformMaxWidth,
          "Stacked Container Transform Max Width",
          Kind.NUMBER, value=0.0, min_value=0.0, max_value=1000.0, step=1.0,
          description=QT_TRANSLATE_NOOP("Nugget", "Maximum width threshold for stacked image container transforms. Type inferred; unverified on-device.")),
    _usol(TweakID.StackedImageContainerModifyTransformMinHeight,
          "Stacked Container Transform Min Height",
          Kind.NUMBER, value=0.0, min_value=0.0, max_value=1000.0, step=1.0,
          description=QT_TRANSLATE_NOOP("Nugget", "Minimum height threshold for triggering stacked image container transforms. Type inferred; unverified on-device.")),
    _usol(TweakID.StackedImageContainerModifyTransformMaxHeight,
          "Stacked Container Transform Max Height",
          Kind.NUMBER, value=0.0, min_value=0.0, max_value=1000.0, step=1.0,
          description=QT_TRANSLATE_NOOP("Nugget", "Maximum height threshold for stacked image container transforms. Type inferred; unverified on-device.")),

    # --- SpringBoard ---
    _t(TweakID.LockScreenFootnote, Section.SPRINGBOARD, "Lock Screen Footnote Text",
       FileLocation.footnote, "LockScreenFootnote", value="", kind=Kind.TEXT,
       description=QT_TRANSLATE_NOOP("Nugget", "Sets custom text shown at the bottom of the Lock Screen below the time. Long text is cut off — keep it short. Leave empty to remove.")),
    _t(TweakID.WatchOSCompatibility, Section.SPRINGBOARD, "Allow pairing with any watchOS version",
       FileLocation.nanoregistry, "", factory=_watchos_compatibility, ipad_only=True,
       description=QT_TRANSLATE_NOOP("Nugget", "Removes the minimum watchOS pairing check in NanoRegistry so you can pair an Apple Watch running any watchOS version with your iPhone.")),
    _t(TweakID.AirDropDisableTimeLimit, Section.SPRINGBOARD, "Disable AirDrop Time Limit for Everyone Option",
       FileLocation.airdrop, "OverrideTimeLimitEveryoneMode",
       description=QT_TRANSLATE_NOOP("Nugget", "Unlocks the hidden 'Everyone' AirDrop receiving option that would normally be limited to a 10-minute time window.")),
    _t(TweakID.SBDontLockAfterCrash, Section.SPRINGBOARD, "Disable Lock After Respring",
       FileLocation.springboard, "SBDontLockAfterCrash",
       description=QT_TRANSLATE_NOOP("Nugget", "Prevents the screen from locking right after a respring — the phone won't ask for a passcode immediately after the UI reloads.")),
    _t(TweakID.SBDontDimOrLockOnAC, Section.SPRINGBOARD, "Disable Screen Dimming While Charging",
       FileLocation.springboard, "SBDontDimOrLockOnAC",
       description=QT_TRANSLATE_NOOP("Nugget", "Stops the display from auto-dimming while the device is connected to a charger.")),
    _t(TweakID.SBHideLowPowerAlerts, Section.SPRINGBOARD, "Disable Low Battery Alerts",
       FileLocation.springboard, "SBHideLowPowerAlerts",
       description=QT_TRANSLATE_NOOP("Nugget", "Suppresses the 'Low Battery — 20% / 10%' system alerts.")),
    _t(TweakID.SBHideACPower, Section.SPRINGBOARD, "Hide AC Power on Lock Screen",
       FileLocation.springboard, "SBHideACPower",
       description=QT_TRANSLATE_NOOP("Nugget", "Hides the charging status from the Lock Screen while the device is plugged into AC power.")),
    _t(TweakID.SBNeverBreadcrumb, Section.SPRINGBOARD, "Disable Breadcrumbs",
       FileLocation.springboard, "SBNeverBreadcrumb",
       description=QT_TRANSLATE_NOOP("Nugget", "Disables the 'Return to <App>' breadcrumb button that appears in the status bar after opening a link from another app.")),
    _t(TweakID.SBShowSupervisionTextOnLockScreen, Section.SPRINGBOARD, "Show Supervision Text on Lock Screen",
       FileLocation.springboard, "SBShowSupervisionTextOnLockScreen",
       description=QT_TRANSLATE_NOOP("Nugget", "Shows the device-supervision text on the Lock Screen, like the '<Device> is supervised by <org>' label seen on MDM-managed devices.")),
    _t(TweakID.AirplaySupport, Section.SPRINGBOARD, "Enable AirPlay support for Stage Manager",
       FileLocation.springboard, "SBExtendedDisplayOverrideSupportForAirPlayAndDontFileRadars",
       description=QT_TRANSLATE_NOOP("Nugget", "Adds extended-display AirPlay support for Stage Manager so apps and external displays can use the feature more broadly.")),
    _t(TweakID.SBMinimumLockscreenIdleTime, Section.SPRINGBOARD, "Auto‑Lock (Lock Screen)",
       FileLocation.springboard, "SBMinimumLockscreenIdleTime", value=5, kind=Kind.NUMBER,
       min_value=0, max_value=600,
       description=QT_TRANSLATE_NOOP("Nugget", "Sets how many minutes of inactivity before the Lock Screen turns the display off. 0 = never auto-lock.")),
    _t(TweakID.SBAlwaysShowSystemApertureInSnapshots, Section.SPRINGBOARD, "Show Dynamic Island in Screenshots",
       FileLocation.springboard, "SBAlwaysShowSystemApertureInSnapshots", min_version="17.4", iphone_only=True,
       description=QT_TRANSLATE_NOOP("Nugget", "Forces the Dynamic Island to appear in screenshots instead of being hidden or shrunk while the screenshot is taken.")),
    _t(TweakID.HideDICompletely, Section.SPRINGBOARD, "Hide Dynamic Island Completely",
       FileLocation.springboard, "SBSuppressDynamicIslandCompletely", min_version="17.4", iphone_only=True,
       description=QT_TRANSLATE_NOOP("Nugget", "Suppresses the Dynamic Island cutout completely so it is never drawn. Can make the screen look odd on devices with a pill cutout.")),
    _t(TweakID.SBShowAuthenticationEngineeringUI, Section.SPRINGBOARD, "Show Red/Green Authentication Line on Lock Screen",
       FileLocation.springboard, "SBShowAuthenticationEngineeringUI",
       description=QT_TRANSLATE_NOOP("Nugget", "Shows a red/green authentication progress indicator on the Lock Screen while Face ID or passcode checks are running (engineering debug UI).")),
    _t(TweakID.UseFloatingTabBar, Section.SPRINGBOARD, "Disable Floating Tab Bar",
       FileLocation.uikit, "UseFloatingTabBar", value=False, ipad_only=True,
       description=QT_TRANSLATE_NOOP("Nugget", "Uses the old fixed tab bar style instead of the floating tab bar on iPad. Enabled when the switch is OFF.")),
    _t(TweakID.SBDisableIconParallax, Section.SPRINGBOARD, "Disable Icon Parallax",
       FileLocation.springboard, "SBDisableParallax",
       description=QT_TRANSLATE_NOOP("Nugget", "Stops Home Screen icons from shifting with the device tilt (the parallax effect). Pair with Disable Icon Page-Control Parallax for a fully static Home Screen.")),

    # --- Internal Options ---
    _t(TweakID.SBBuildNumber, Section.INTERNAL, "Show Build Version in Status Bar", GP, "UIStatusBarShowBuildVersion",
       description=QT_TRANSLATE_NOOP("Nugget", "Displays the iOS build number (e.g. 21A5284a) in the status bar next to the iOS version.")),
    _t(TweakID.RTL, Section.INTERNAL, "Force Right-to-Left Layout", GP, "NSForceRightToLeftWritingDirection",
       description=QT_TRANSLATE_NOOP("Nugget", "Forces a right-to-left layout for the entire system, mirroring the UI as if your primary language were RTL.")),
    _t(TweakID.LTR, Section.INTERNAL, "Force Left-to-Right Layout", GP, "NSForceLeftToRightWritingDirection",
       description=QT_TRANSLATE_NOOP("Nugget", "Forces a left-to-right layout across the whole system regardless of the RTL language setting.")),
    _t(TweakID.SBIconVisibility, Section.INTERNAL, "Show Hidden Icons on Home Screen", GP, "SBIconVisibility",
       description=QT_TRANSLATE_NOOP("Nugget", "Reveals hidden or disabled Home Screen icons, including internal placeholder icons that are normally not drawn.")),
    _t(TweakID.iMessageDiagnosticsEnabled, Section.INTERNAL, "iMessage Debugging", GP, "iMessageDiagnosticsEnabled",
       description=QT_TRANSLATE_NOOP("Nugget", "Enables the iMessage engineering debug menu / diagnostics inside the Messages app.")),
    _t(TweakID.IDSDiagnosticsEnabled, Section.INTERNAL, "Continuity Debugging", GP, "IDSDiagnosticsEnabled",
       description=QT_TRANSLATE_NOOP("Nugget", "Enables the Continuity engineering debug diagnostics in Settings (Apple ID and related sections).")),
    _t(TweakID.VCDiagnosticsEnabled, Section.INTERNAL, "FaceTime Debugging", GP, "VCDiagnosticsEnabled",
       description=QT_TRANSLATE_NOOP("Nugget", "Enables FaceTime / VoIP engineering debug diagnostics.")),
    _t(TweakID.AccessoryDeveloperEnabled, Section.INTERNAL, "Show Accessory Developer Settings", GP, "AccessoryDeveloperEnabled",
       description=QT_TRANSLATE_NOOP("Nugget", "Adds a hidden Accessory Developer settings page to the Settings app for testing accessories.")),
    _t(TweakID.DisableSecondsHand, Section.INTERNAL, "Disable Clock Icon Seconds Hand", GP, "SBDisableClockIconSecondsHand",
       description=QT_TRANSLATE_NOOP("Nugget", "Stops the animated second hand on the Clock app's Home Screen icon.")),
    _t(TweakID.DisableSearchingWebsites, Section.INTERNAL, "Disable Spotlight Searching in Websites", GP, "SBSearchDisabledDomains",
       description=QT_TRANSLATE_NOOP("Nugget", "Removes website / web search results from Spotlight search suggestions.")),
    _t(TweakID.ShowButtonHints, Section.INTERNAL, "Show Hardware Button Hints in Screenshots", GP, "SBHardwareButtonHintDropletsAlwaysVisibleInSnapshots",
       description=QT_TRANSLATE_NOOP("Nugget", "Shows the side button / action button hint labels in screenshots (engineering debug UI).")),
    _t(TweakID.AppStoreDebug, Section.INTERNAL, "App Store Debug Gesture", FileLocation.appStore, "debugGestureEnabled",
       description=QT_TRANSLATE_NOOP("Nugget", "Enables the hidden debug gesture in the App Store app, used to dump store data and inspect the store backend.")),
    _t(TweakID.NotesDebugMode, Section.INTERNAL, "Notes Debug Mode", FileLocation.notes, "DebugModeEnabled",
       description=QT_TRANSLATE_NOOP("Nugget", "Turns on the Notes app debug menu for engineering debugging.")),
    _t(TweakID.BKDigitizerVisualizeTouches, Section.INTERNAL, "Show Touches With Debug Info", FileLocation.backboardd, "BKDigitizerVisualizeTouches",
       description=QT_TRANSLATE_NOOP("Nugget", "Visually marks every touch point on the screen with debugging information as you touch. Great for diagnosing touch issues.")),
    _t(TweakID.BKHideAppleLogoOnLaunch, Section.INTERNAL, "Hide Respring Icon", FileLocation.backboardd, "BKHideAppleLogoOnLaunch",
       description=QT_TRANSLATE_NOOP("Nugget", "Hides the Apple logo animation during respring, showing a black screen instead until the UI comes back.")),
    _t(TweakID.EnableWakeGestureHaptic, Section.INTERNAL, "Vibrate on Raise-to-Wake", FileLocation.coreMotion, "EnableWakeGestureHaptic",
       description=QT_TRANSLATE_NOOP("Nugget", "Plays a Taptic Engine vibration when the device wakes via the raise-to-wake gesture.")),
    _t(TweakID.PlaySoundOnPaste, Section.INTERNAL, "Play Sound on Paste", FileLocation.pasteboard, "PlaySoundOnPaste",
       description=QT_TRANSLATE_NOOP("Nugget", "Plays a sound every time content is pasted anywhere on the device.")),
    _t(TweakID.AnnounceAllPastes, Section.INTERNAL, "Show Notifications for System Pastes", FileLocation.pasteboard, "AnnounceAllPastes",
       description=QT_TRANSLATE_NOOP("Nugget", "Shows a system notification whenever an app reads the pasteboard, acting as a privacy indicator for system-level pastes.")),
)

SPECS_BY_SECTION = {section: [s for s in SPECS if s.section == section and not s.disabled] for section in Section}
SPECS_BY_ID = {spec.id: spec for spec in SPECS if not spec.disabled}