from enum import Enum, auto

class TweakID(Enum):
    # tweaks page
    PosterBoard = auto()
    Templates = auto()
    StatusBar = auto()

    # springboard
    LockScreenFootnote = auto()
    WatchOSCompatibility = auto()
    AirDropDisableTimeLimit = auto()
    SBDontLockAfterCrash = auto()
    SBDontDimOrLockOnAC = auto()
    SBHideLowPowerAlerts = auto()
    SBHideACPower = auto()
    SBNeverBreadcrumb = auto()
    SBShowSupervisionTextOnLockScreen = auto()
    AirplaySupport = auto()
    SBMinimumLockscreenIdleTime = auto()
    SBAlwaysShowSystemApertureInSnapshots = auto()
    HideDICompletely = auto()
    SBShowAuthenticationEngineeringUI = auto()
    UseFloatingTabBar = auto()
    SBDisableIconParallax = auto()

    # internal
    SBBuildNumber = auto()
    RTL = auto()
    LTR = auto()
    SBIconVisibility = auto()
    MetalForceHudEnabled = auto()
    iMessageDiagnosticsEnabled = auto()
    IDSDiagnosticsEnabled = auto()
    VCDiagnosticsEnabled = auto()
    AccessoryDeveloperEnabled = auto()

    DisableSecondsHand = auto()
    DisableSearchingWebsites = auto()
    ShowButtonHints = auto()

    AppStoreDebug = auto()
    NotesDebugMode = auto()
    BKDigitizerVisualizeTouches = auto()
    BKHideAppleLogoOnLaunch = auto()
    EnableWakeGestureHaptic = auto()
    PlaySoundOnPaste = auto()
    AnnounceAllPastes = auto()

    # liquid glass
    ForceSolariumFallback = auto()
    DisableSolarium = auto()
    IgnoreSolariumLinkedOnCheck = auto()
    NoLiquidClock = auto()
    NoLiquidDock = auto()
    DisableSpecularMotion = auto()
    DisableOuterRefraction = auto()
    DisableSolariumHDR = auto()
    # iOS 27 additions
    DisallowGlassButtons = auto()
    DisallowGlassLockScreen = auto()
    ForceEnhancedSpeculars = auto()
    ForceSolariumIntelligence = auto()
    UISolariumFallback = auto()
    IgnoreSolariumHardwareCheck = auto()
    IgnoreSolariumOptOut = auto()
    DisableSpecularEverywhere = auto()
    # SpringBoard home-screen glass family (same preference table as the keys
    # above; read by SpringBoard from com.apple.springboard, all Bool)
    DisableWidgetSpecular = auto()
    DisableDockSpecular = auto()
    DisableFolderSpecular = auto()
    ExcludeClearGlassShadows = auto()
    ExcludeDockShadow = auto()
    ExcludeSearchShadow = auto()
    UseFlatIconsEverywhere = auto()

    # Tier 3: SwiftUI / UIKit debug switches (UserDefaults, read via GP)
    GlassContainerLogging = auto()
    FlexiGlassMacOS = auto()
    FlexiGlassMacOSPointer = auto()
    InvisibilitySuppressesGlass = auto()
    EnableGlassEffectBridgeLayers = auto()
    EnableGaussianGlassEffectBridgeLayers = auto()
    UnifiedSystemBackgroundColorsEnabled = auto()
    UnaryGlassContainerEnabled = auto()
    EnableSolariumCompactChrome = auto()
    DisableSolariumCompactChrome = auto()

    # Tier 4: DesignLibrary glass recipes (GP)
    SolariumIncreasedDiffusion = auto()
    SolariumUseDisplayAngle = auto()
    SolariumTintMask = auto()
    SolariumBackgroundFilter = auto()
    SolariumHighlightWhite = auto()
    SolariumLiveTuning = auto()
    SolariumHierarchicalStyle = auto()
    GlassHierarchicalStyle = auto()
    GlassVisualDebug = auto()
    GlassVisualWarnings = auto()
    BlurFillExperiment = auto()
    AdaptiveGlassHysteresisDarkRange = auto()
    AdaptiveGlassHysteresisLightRange = auto()
    CalistogaLargeRefraction = auto()
    CalistogaRegularClearer = auto()
    CalistogaBackdropMarginIncludesBlur = auto()
    CalistogaAllowLumaTracking = auto()
    CalistogaSidebarAccentOpacity = auto()
    CalistogaPerceptualBackdropScale = auto()
    CalistogaKeyboardGlass = auto()
    CalistogaCameraGlass = auto()

    # Tier 5: UISolarium* floating content / stacked icon motion (GP, numeric)
    FloatingContentViewSpecularHighlightOpacity = auto()
    FloatingContentViewUnfocusedBorderOpacity = auto()
    FloatingContentViewUnfocusedBorderWidth = auto()
    FloatingContentViewEnableBackgroundFills = auto()
    FloatingContentViewDebugBackgroundFills = auto()
    FloatingContentViewPunchoutShadow = auto()
    FloatingContentViewModifyTransformMode = auto()
    FloatingContentViewOverrideRotationX = auto()
    FloatingContentViewOverrideRotationY = auto()
    FloatingContentViewOverrideTranslationX = auto()
    FloatingContentViewOverrideTranslationY = auto()
    FloatingContentViewModifyRotationStrength = auto()
    FloatingContentViewModifyTranslationStrength = auto()
    FocusSpecularHighlightMaxSize = auto()
    FocusSpecularHighlightScaleFactor = auto()
    FocusSpecularHighlightSensitivity = auto()
    FocusSpecularHighlightNormalizedPositionX = auto()
    FocusSpecularHighlightNormalizedPositionY = auto()
    NewStackedImageRenderingEnabled = auto()
    NewStackedImageFiltersEnabled = auto()
    NewStackedImage3DTransformsEnabled = auto()
    NewStackedImage3DTransformedGlassLayer = auto()
    NewStackedImageSpecularEnabled = auto()
    NewStackedImageSpecularOpacity = auto()
    NewStackedImageRadiosityEnabled = auto()
    NewStackedImageForceAdjustMotionForSize = auto()
    NewStackedImageForceDefaultScaleSizeIncrease = auto()
    NewStackedImageInnerParallaxScale = auto()
    NewStackedImageAsymmetricScale = auto()
    NewStackedImageProgressiveScale = auto()
    NewStackedImageAdditionalTranslation = auto()
    NewStackedImageFocusedAdditionalScaleAmount = auto()
    StackedImageContainerDefaultMaxDepth = auto()
    StackedImageContainerDefaultRotationX = auto()
    StackedImageContainerDefaultRotationY = auto()
    StackedImageContainerDefaultTranslationX = auto()
    StackedImageContainerDefaultTranslationY = auto()
    StackedImageContainerModifyMaxDepthStrength = auto()
    StackedImageContainerModifyRotationStrength = auto()
    StackedImageContainerModifyTranslationStrength = auto()
    StackedImageContainerModifyInnerParallaxScaleStrength = auto()
    StackedImageContainerModifyTransformMinWidth = auto()
    StackedImageContainerModifyTransformMaxWidth = auto()
    StackedImageContainerModifyTransformMinHeight = auto()
    StackedImageContainerModifyTransformMaxHeight = auto()

    # daemons
    Daemons = auto()
    ClearScreenTimeAgentPlist = auto()